### ISSUE TITLE
Message

### ISSUE THREAD

**Issue by sqdldev** [Figseu-Technology/G62#5]
Since you have re-published this repository, I will take that as a sign to re-publish my utilities as well. Not only have I contradicted myself, but you have contradicted yourself as well.

**Comment by sqdldev** [comment]
Just because somebody does something that might get them in trouble does not mean that you should follow in their footsteps.

**Comment by Figseu-Technology** [comment]
Surely you deleted Tileset, but not Tile Lookup.

Furthermore, since you still seem to be twisting the facts, I'm going to declare the negotiation broken.

**Comment by sqdldev** [comment]
There was no negotiation to begin with.

Let me state what has happened:

- Person who I do not know randomly steals the code for my website presenting it as their own
- I tell the person why the website was taken down
- Person does not budge, instead accuses me of doing something to them that I do not remember, refuses to elaborate
- Asks me to take down my site, while also putting up a copy of my site by themselves
- I do not understand the logic of this.

From my perspective, all I see is nonsense. I do not understand why you are copying my site to make me take it down. You always refuse to elaborate any more than 2 sentences, and therefore I cannot find a good reason for me to do anything you say.

**Comment by sqdldev** [comment]
I had never cared about the "negotiation" that you had never officially made. You should understand that I took my Level Editor down because I didn't want to keep maintaining it and also wanted to avoid legal trouble.

MiniMax is releasing their own Level Editor, and therefore provided all the more reason for me to take my website down.

From my perspective, you are the one twisting the facts.
